### ISSUE TITLE
您文章中的六组数据集从哪里可以下载呢？

### ISSUE THREAD

**Issue by adengna1** [yulisun/INLPG#1]
您好，我是图像变化检测的初学者，阅读了您的“Structure Consistency based Graph for Unsupervised Change Detection with Homogeneous and Heterogeneous Remote Sensing Images”文章，您做的非常好。我看到您的Github文档中只提供了部分数据，想询问您一下，您文章中的六组数据集从哪里可以下载呢？非常希望您能提供帮助。

**Comment by yulisun** [comment]
sunyuli@mail.ustc.edu.cn ，可以通过邮件联系吗

**Comment by adengna1** [comment]
好的，用邮件联系您了。
