### ISSUE TITLE
请求Texas数据集与Sardinia数据集光学与SAR变化检测数据集

### ISSUE THREAD

**Issue by ChengPeng0376** [yulisun/INLPG#2]
作者您好，我是研究方向为变化检测的一名学生，正苦于寻找光学与SAR变化检测数据集，冒昧请求作者能否发送Texas数据集与Sardinia数据集，不甚感激。谢谢。12023132008@stu.nxu.edu.cn

**Comment by yulisun** [comment]
相关信息已发送你邮件了~~请查收

**Comment by ChengPeng0376** [comment]
邮箱已收到, 非常感谢孙博士。真心祝福~~~

**Comment by zty-acc** [comment]
孙博士你好，我也是研究变化检测的一名学生，我目前也在找Texas数据集和Sardinia数据集，想向您请求这两个数据集以供研究使用。希望您能在方便时将数据集发送至我的邮箱1830211287@qq.com 。对此，我将不胜感激。

**Comment by yulisun** [comment]
同学你好，相关数据集下载信息已发送你邮件了~~请查收

**Comment by zty-acc** [comment]
孙博您好，已经收到啦，感谢感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yulisun/INLPG"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月6日(星期二) 上午10:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yulisun/INLPG] 请求Texas数据集与Sardinia数据集光学与SAR变化检测数据集 (Issue #2)





 
同学你好，相关数据集下载信息已发送你邮件了~~请查收

**Comment by Dap1Aa** [comment]
孙博士你好，我也是研究变化检测的一名学生，我目前也在找Texas数据集和Sardinia数据集，想向您请求这两个数据集以供研究使用。希望您能在方便时将数据集发送至我的邮箱[1935231643@qq.com](mailto:1935231643@qq.com) 。对此，我将不胜感激。

**Comment by yulisun** [comment]
已发送，祝好！
